version: '3.9'

services:
  django-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DJANGO_DB_HOST=db
      - DJANGO_DB_NAME=weather_db
      - DJANGO_DB_USER=root
      - DJANGO_DB_PASSWORD=example
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: mysql_db_1
    ports:
      - "3309:3306"
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: weather_db_1
      MYSQL_USER: user
      MYSQL_PASSWORD: saifch
    volumes:
      - mysql_data:/var/lib/mysql

  prometheus:
    image: prom/prometheus
    container_name: prometheus1
    ports:
      - "9091:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana
    container_name: grafana1
    ports:
      - "3001:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana_data:/var/lib/grafana

  node-exporter:
    image: prom/node-exporter
    container_name: node_exporter
    ports:
      - "9100:9100"

volumes:
  mysql_data:
  grafana_data:
