# Generated by Django 4.2.17 on 2024-12-26 12:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferred_city', models.CharField(choices=[('Tunis', 'Tunis'), ('Sfax', 'Sfax'), ('Sousse', 'Sousse'), ('Kairouan', 'Kairouan'), ('Bizerte', 'Bizerte'), ('Gabes', 'Gabes'), ('Ariana', 'Ariana'), ('Nabeul', 'Nabeul'), ('Tozeur', 'Tozeur'), ('Monastir', 'Monastir'), ('Gafsa', 'Gafsa')], max_length=100)),
                ('preferred_unit', models.CharField(choices=[('Celsius', 'Celsius'), ('Fahrenheit', 'Fahrenheit')], max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
