# Generated by Django 4.2.17 on 2024-12-26 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0003_remove_userpreference_preferred_city_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Widget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('widget_type', models.CharField(choices=[('chart', 'Chart'), ('map', 'Map'), ('table', 'Table')], max_length=255)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
