# Generated by Django 4.2.17 on 2024-12-26 17:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('weather', '0004_widget'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('element_type', models.CharField(choices=[('temperature', 'Temperature'), ('humidity', 'Humidity'), ('wind_speed', 'Wind Speed'), ('precipitation', 'Precipitation'), ('pressure', 'Pressure'), ('cloud_coverage', 'Cloud Coverage')], max_length=20)),
                ('description', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Widget',
        ),
        migrations.RemoveField(
            model_name='userpreference',
            name='layout',
        ),
        migrations.RemoveField(
            model_name='userpreference',
            name='preferred_widgets',
        ),
        migrations.RemoveField(
            model_name='userpreference',
            name='theme',
        ),
        migrations.AlterField(
            model_name='userpreference',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userpreference',
            name='preferred_elements',
            field=models.ManyToManyField(to='weather.weatherelement'),
        ),
    ]
