# Generated by Django 4.2.17 on 2024-12-27 23:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('weather', '0005_weatherelement_delete_widget_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_location', models.CharField(blank=True, max_length=255, null=True)),
                ('favorite_locations', models.JSONField(default=list)),
                ('language', models.CharField(choices=[('en', 'English'), ('fr', 'French')], default='en', max_length=10)),
                ('temperature_units', models.CharField(choices=[('Celsius', 'Celsius'), ('Fahrenheit', 'Fahrenheit')], default='Celsius', max_length=10)),
                ('alert_temp_over_35', models.BooleanField(default=False)),
                ('alert_rain', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='UserPreference',
        ),
        migrations.DeleteModel(
            name='WeatherElement',
        ),
    ]
