# Generated by Django 4.2.17 on 2024-12-30 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0006_userpreferences_delete_userpreference_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('weather_type', models.CharField(max_length=50)),
                ('description', models.TextField()),
            ],
        ),
    ]
