# Generated by Django 5.1.5 on 2025-01-30 13:00

from django.db import migrations

def add_default_places(apps, schema_editor):
    # Get the Place model dynamically using apps.get_model
    Place = apps.get_model('weather', 'Place')
    # Add default places
    Place.objects.create(name="Carthage", location="Tunis", weather_type="Sunny, Overcast Clouds", description="An ancient city known for its historical ruins, including the famous Roman Baths, amphitheater, and ancient port.")
    Place.objects.create(name="Dougga", location="Beja", weather_type="Sunny, Overcast Clouds", description=" is an ancient Roman archaeological site located in northern Tunisia, about 110 kilometers southwest of Tunis.")
    Place.objects.create(name="El Djem", location="Mahdia", weather_type="Sunny, Clear Sky", description="A UNESCO World Heritage site known for its well-preserved Roman amphitheater, one of the largest in the world.")
    Place.objects.create(name="Sidi Bou Said", location="Tunis", weather_type="Sunny, Light Breeze", description="A charming seaside village known for its white and blue buildings, offering picturesque views of the Mediterranean Sea.")
    Place.objects.create(name="El Djem", location="Mahdia", weather_type="Sunny, Clear Sky", description="A UNESCO World Heritage site known for its well-preserved Roman amphitheater, one of the largest in the world.")
    Place.objects.create(name="Douz", location="Southern Tunisia", weather_type="Hot, Dry", description="Often referred to as the 'Gateway to the Sahara,' Douz is famous for its desert festivals, camel treks, and unique cultural experiences in the heart of the desert.")
    Place.objects.create(name="Kairouan", location="kairouan", weather_type="Sunny, Mild", description="A UNESCO World Heritage site known for its historical mosques, including the Great Mosque of Kairouan, which is one of the most important Islamic sites in Tunisia.")
    Place.objects.create(name="Hammamet", location="North-eastern Tunisia, on the Mediterranean coast", weather_type="Sunny, Mild", description="Famous for its beaches, resorts, and charming medina, Hammamet is a popular destination for beach lovers and those seeking a vibrant coastal atmosphere.")
    Place.objects.create(name="Matmata", location="Gabes", weather_type="Hot, Dry, Overcast Clouds", description="Known for its troglodyte dwellings, Matmata is home to traditional cave houses. The unique architecture and the surrounding desert landscape make it an interesting destination.")
    Place.objects.create(name="Tataouine", location="Southern Tunisia", weather_type="Hot, Dry", description="Famous for its troglodyte dwellings and kasbahs, Tataouine is a place of historical interest and was used as a filming location for Star Wars.")
    Place.objects.create(name="El Kef", location="North-western Tunisia", weather_type="Mild, Cool", description="Known for its charming countryside, El Kef is a scenic town with beautiful views, historical sites like the old city walls, and proximity to the Tiberias River.")
    Place.objects.create(name="Chott El Jerid", location="Kebili", weather_type="Hot, Clear Sky", description="A vast salt flat in the south of Tunisia, known for its breathtaking desert landscapes and unique ecosystem.")
    Place.objects.create(name="Zitouna Mosque", location="Tunis", weather_type="Mild, Partly Cloudy", description="A historical mosque located in the heart of Tunis, known for its stunning architecture and cultural significance.")
    Place.objects.create(name="Bardo Museum", location="Tunis", weather_type="Mild, Overcast", description="A museum in Tunis, famous for its extensive collection of Roman mosaics and artifacts from Tunisia's history.")
    Place.objects.create(name="Ksar Ouled Soltane", location="Gabes", weather_type="Hot, Clear Sky", description="A traditional Berber fortified village in the south of Tunisia, known for its unique architecture and as a filming location for Star Wars.")
    Place.objects.create(name="Tabarka", location="Jendouba", weather_type="Mild, Partly Cloudy", description="A coastal town known for its beautiful beaches, coral reefs, and the Genoese Fort, offering a peaceful retreat for nature lovers.")
    Place.objects.create(name="Ksar Ouled Debbab", location="Tozeur", weather_type="Hot, Clear Sky", description="An ancient fortified village with traditional Berber architecture, often used in films, including scenes from 'Star Wars'.")
    Place.objects.create(name="Bulla Regia", location="Jendouba", weather_type="Sunny, Overcast Clouds", description="An ancient Roman site known for its well-preserved underground houses, offering a glimpse into ancient life in Tunisia.")
    Place.objects.create(name="Tunis Medina", location="Tunis", weather_type="Mild, Partly Cloudy", description="A UNESCO World Heritage site, with winding streets full of vibrant souks, mosques, and historical monuments.")
    Place.objects.create(name="Cave of Aoudia", location="Tataouine", weather_type="Hot, Clear Sky", description="A unique cave in the southern desert area of Tunisia, offering a distinctive landscape and a place for exploration.")
    Place.objects.create(name="Ong Jemel", location="Tozeur", weather_type="Hot, Clear Sky", description="A stunning desert location, famous for its otherworldly rock formations and being a filming location for several Star Wars movies.")
    Place.objects.create(name="Bizerte", location="Bizerte", weather_type="Sunny, Clear Sky", description="A northern coastal city with a charming old town, Mediterranean beaches, and rich history, including the famous Bizerte Harbour.")
    Place.objects.create(name="La Marsa", location="Tunis", weather_type="Mild, Partly Cloudy", description="A seaside suburb known for its beautiful beaches, calm atmosphere, and vibrant cultural scene, ideal for relaxation.")
    Place.objects.create(name="Nefta", location="Kebili", weather_type="Hot, Clear Sky", description="A charming oasis town with palm groves, traditional architecture, and a serene atmosphere, often seen as a gateway to the desert.")
    Place.objects.create(name="Ras El Rmal", location="Tunis", weather_type="Sunny, Clear Sky", description="A picturesque beach located in the north of Tunisia, offering pristine white sand and crystal-clear waters, ideal for relaxation.")
    Place.objects.create(name="Douz", location="Kebili", weather_type="Hot, Clear Sky", description="Often referred to as the 'Gateway to the Sahara,' Douz is known for its desert landscapes, camel rides, and the famous Douz Festival.")
    Place.objects.create(name="Ghar El Melh", location="Bizerte", weather_type="Mild, Partly Cloudy", description="A quaint fishing village located near the northern tip of Tunisia, known for its scenic beauty, salt flats, and historical ruins.")
    Place.objects.create(name="Tunis Zoo", location="Tunis", weather_type="Mild, Partly Cloudy", description="A family-friendly destination featuring a variety of wildlife and beautiful landscapes, offering a great day out for nature lovers.")
    Place.objects.create(name="Medenine", location="Medenine", weather_type="Hot, Clear Sky", description="Known for its traditional architecture and proximity to the desert, Medenine is a historic town that showcases the best of Tunisia’s southern culture.")
    Place.objects.create(name="Kairouan Mosque", location="Kairouan", weather_type="Mild, Partly Cloudy", description="The Great Mosque of Kairouan is one of the holiest sites in Tunisia, with impressive architecture and a rich history dating back to the 7th century.")
    Place.objects.create(name="Jebel Chambi", location="Kasserine", weather_type="Mild, Overcast", description="Tunisia's highest peak, Jebel Chambi offers stunning views of the surrounding mountains and a variety of hiking trails for nature enthusiasts.")


class Migration(migrations.Migration):
    dependencies = [
        ("weather", "0007_place"),  # This is your previous migration
    ]

    operations = [
        migrations.RunPython(add_default_places),
    ]