name: Django CI/CD Pipeline

on:
  push:
    branches: [ "main" ]  # Trigger on push to the main branch
  pull_request:
    branches: [ "main" ]  # Trigger on pull requests to the main branch

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v4

    # Step 2: Set up Docker Buildx
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    # Step 3: Log in to Docker Hub
    - name: Log in to Docker Hub
      run: |
        echo "${{ secrets.DOCKER_ACCESS_TOKEN }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    # Step 4: Build the base Docker image
    - name: Build base Docker image
      run: |
        docker build -t my-django-app-base -f Dockerfile.base .

    # Step 5: Build the final Docker image
    - name: Build final Docker image
      run: |
        docker build -t my-django-app -f Dockerfile .

    # Step 6: Run tests (optional)
    # - name: Run Django tests
    #   run: |
    #     docker run --rm my-django-app python manage.py test

    # Step 7: Tag the Docker image
    - name: Tag Docker image
      run: |
        docker tag my-django-app ${{ secrets.DOCKER_USERNAME }}/my-django-app:latest

    # Step 8: Push the Docker image to Docker Hub
    - name: Push Docker image to Docker Hub
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/my-django-app:latest