name: Docker Compose CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    # Step 1: Build the base Docker image
    - name: Build the base Docker image
      run: docker build -t my-weather-app-base -f Dockerfile.base .

    # Step 2: Set up Docker Compose
    - name: Set up Docker Compose
      run: docker-compose up -d

    # Step 3: Run tests or other commands (optional)
    - name: Run tests
      run: docker-compose exec django-app python manage.py test

    # Step 4: Tear down Docker Compose (optional)
    - name: Tear down Docker Compose
      if: always()
      run: docker-compose down