name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    # Step 1: Build the base image
    - name: Build the base Docker image
      run: docker build -t my-weather-app-base -f Dockerfile.base .

    # Step 2: Build the main Docker image
    - name: Build the main Docker image
      run: docker build -t my-image-name:$(date +%s) -f Dockerfile .