name: CI/CD Pipeline for Django App

on:
  push:
    branches:
      - main
  pull_request:

env:
  IMAGE_NAME: django-app

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      # Start MySQL database service
      - name: Start MySQL container
        run: |
          docker run -d --name test-mysql \
          -e MYSQL_ROOT_PASSWORD=testpassword \
          -e MYSQL_DATABASE=testdb \
          -e MYSQL_USER=testuser \
          -e MYSQL_PASSWORD=testpassword \
          -p 3309:3306 mysql:8.0
          sleep 20 # Allow MySQL to initialize

      # Build the Docker image
      - name: Build Docker image
        run: docker build -t ${{ env.IMAGE_NAME }}:latest .

      # Push the Docker image to Docker Hub
      - name: Push Docker image to Docker Hub
        run: |
          docker tag ${{ env.IMAGE_NAME }}:latest ${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push

    steps:
      # Deploy the application using Docker Compose
      - name: Deploy containers using Doc
