name: Build & Deploy Django Application

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build and Deploy Application
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        ports:
          - 3309:3306
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: weather_db
          MYSQL_USER: user
          MYSQL_PASSWORD: saifch
        options: --health-cmd="mysqladmin ping --silent" --health-interval=10s --health-timeout=5s --health-retries=3

     steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set Up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Install System Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc libmariadb-dev libmariadb-dev-compat pkg-config

      - name: Install Python Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --no-cache-dir --find-links=/app/pip_cache -r requirements.txt --default-timeout=100

      - name: Run Migrations
        run: |
          python manage.py migrate

      - name: Run Tests
        run: |
          python manage.py test

      - name: Build Docker Image
        uses: docker/build-push-action@v2
        with:
          context: .
          dockerfile: Dockerfile
          push: false
          tags: ${{ secrets.DOCKER_USERNAME }}/django-app:latest

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      - name: Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: .
          dockerfile: Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/django-app:latest

      - name: Deploy Application (Optional Step)
        run: |
          echo "Deployment steps go here. For example, SSH into the server and deploy the app."